import java.util.Random;

public class T1Q7 {
    public static void main(String[] args) {
        Random random = new Random();

        int[] GeneratedNumber = new int[10];
        int MAX = 101;
        int MIN = 10;

        for(int i = 0; i < 10; i++){
            GeneratedNumber[i] = random.nextInt(MIN, MAX);
            System.out.println("Random Number " + (i+1) + ": " + GeneratedNumber[i]);
        }

        EvenorOdd(GeneratedNumber);
    }

    public static void EvenorOdd(int[] GeneratedNumber){
        int evencount = 0;
        int oddcount = 0;

        for(int nums: GeneratedNumber){
            if(nums % 2 == 0){
                evencount++;
            }else{
                oddcount++;
            }
        }

        // Print how many even or odd number in 10 Generated numbers
        System.out.println("\nResults:");
        System.out.println("Number of even numbers: " + evencount);
        System.out.println("Number of odd numbers: " + oddcount);

        System.out.println();

        // Print all even or odd numbers
        System.out.println("\nEven numbers:");
        for(int even : GeneratedNumber){
            if(even % 2 == 0){
                System.out.print(even + " ");
            }
        }

        System.out.println();
        
        System.out.println("\nOdd numbers:");
        for(int odd : GeneratedNumber){
            if(odd % 2 != 0){
                System.out.print(odd + " ");
            }
        }
    }
}

// Print the number of odd and even number from 10 random numbers generated by computer. The random number must be from 10 – 100